name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: 'Build and Test on ${{ matrix.python-version }}, experimental: ${{ matrix.experimental }}'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        experimental: [false]
        # include:
        #   - python-version: "3.11"
        #     experimental: true
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dev dependencies
        run: |
          poetry install --with dev

      - name: Run Tests
        run: poetry run ./run-tests.sh
